### ISSUE TITLE
Suggestion for textures

### ISSUE THREAD

**Issue by blockbreaker1361** [Soartex/Issues#3]
Is there any way possible to get textures made for Redtone Arsenal mod? It's part of the Cofh family of mods. Thanks for your time. Have a wonderful day. :)

**Comment by DrZed** [comment]
https://github.com/Soartex-Modded/Modded-1.7.x/commit/ccb8ae5837128e49488d56ebb86106b86166324e
https://github.com/Soartex-Modded/Modded-1.7.x/tree/master/Redstone_Arsenal/assets/redstonearsenal/textures/items/tool
Apparently it has been done
Close this "Issue"

**Comment by blockbreaker1361** [comment]
That didn't take long. Only 1 whole year.

**Comment by DrZed** [comment]
I would've done it if I saw it sooner, but meh, it's done. Anyway if you haven't noticed there isn't many contributers to the resource pack.... Not to mention textures take a thing called, effort to make.

**Comment by Shoeboxam** [comment]
I had actually created support for this mod, way back in the ether, but was trying to start up an Invictus patch system at the time. So, if you used Invictus, it would have been complete. This wasn't very well communicated. Ultimately, I decided to just lump it into the Fanver support and subsequently donated it to Fanver, even though the textures are from Invictus.

I have this, so far, but I've decided to break it off into its own application.
https://github.com/Shoeboxam/Gitstream

**Comment by Shoeboxam** [comment]
There is a slack group for artists/contributors, @DrZed, if you're interested. I'm currently spending time on tooling. I feel that a java application that wraps the technical work of pull requests, manipulating the repository into a testable resource pack, and tracking user edits will reduce the barrier of entry for new artists- I just set up a new computer, and the process of building the texture development environment is entirely too complicated.

**Comment by DrZed** [comment]
I just woke up, can you put it simpler what you're asking of me @Shoeboxam xD. It feels as if you want me to make a program that interacts with github pulling new edits and turns them into zips for pack testing.

Nice mod (Gitstream), Little known fact you can use a folder as a resource pack, and it updates when you reload resource packs, so you can make it pull the resources into the file load it as a resource pack, and done. I do this when editing soartex for my own usage, for mods you don't yet have, but I don't feel my textures meet your standards.

**Comment by Shoeboxam** [comment]
@DrZed: Sorry! I didn't mean it that way. You noticed there weren't many contributors, which is accurate. In response, I explained why I think that is the case, and also what I'm doing to improve the situation- I'm writing a java application that handles the technical bits that most likely turn people away from the project.  
I also wanted to invite you to our chat group, if you're interested. I feel like open chat is a great way to keep a little community like ours going. I don't expect regular contributions or anything... it's always nice just to be able to speak up about a broken texture, or throw your opinion in on the stuff that gets committed. I primarily want to build up the community we had over the first few years of my work on the pack. Since I've largely been "missing in action" for a few years, I know it will take some work to get the ball rolling again. ;)

**Comment by DrZed** [comment]
Sure, I'll accept the invite.
I'll even attempt to make contributions :P

**Comment by Shoeboxam** [comment]
Sweet, I'll need your slack email address. If you're not comfortable putting it up here, you can email it to Shoeboxam@gmail.com.

**Comment by DrZed** [comment]
kyahne14@gmail.com
